name: hive_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  go_router: ^14.8.1
  flutter_slidable: ^4.0.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  http: ^1.3.0
  xml: ^6.5.0
  url_launcher: ^6.3.1
  dart_rss: ^3.0.3
  shared_preferences: ^2.5.2
  hugeicons: ^0.0.7
  flutter_staggered_animations: ^1.1.1
  auto_route: ^10.0.0
  flutter_svg: ^2.0.8
  image_picker: ^1.1.2
  glassmorphism: ^3.0.0
  timezone: ^0.10.0
  lottie: ^3.3.1
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^4.3.0
  flutter_animated_progress_bar: ^1.0.5
  add_2_calendar: ^3.0.1
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.7
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  uuid: ^4.3.3
  flutter_native_splash: ^2.3.10
  # Image processing packages
  image: ^4.1.3
  path: ^1.8.3
  # Firebase packages
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_analytics: ^10.4.3
  firebase_messaging: ^14.6.3
  google_sign_in: ^6.1.4
  # Temporarily removing workmanager due to compatibility issues
  # workmanager: ^0.5.2
  connectivity_plus: ^4.0.2
  firebase_crashlytics: ^3.3.3
  mime: ^1.0.4
  get_it: ^7.6.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  visibility_detector: ^0.4.0+2
  flutter_blurhash: ^0.7.0
  firebase_remote_config: ^4.2.3
  package_info_plus: ^4.1.0
  palette_generator: ^0.3.3+2
  firebase_database: ^10.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  confetti: ^0.8.0
  flutter_phoenix: ^1.1.1
  photo_view: ^0.15.0

  path_provider: any
  timeago: ^3.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/component-6.png
    - assets/images/google.png
    - assets/images/hivelogo.png
    - assets/images/whereyoulive.png
    - assets/images/realbooks.png
    - assets/images/house.png
    - assets/images/megaphone.png
    - assets/images/hivebeaker.png
    - assets/images/circles.png
    - assets/images/year.png
