name: hive_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  http: ^0.13.5
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/books.png
    - assets/images/component-6.png
    - assets/images/google.png
    - assets/images/hivelogo.png
    - assets/images/whereyoulive.png
    - assets/images/profile.png
    - assets/images/friend1.png
    - assets/images/friend2.png
