// Mocks generated by Mockito 5.4.6 from annotations
// in hive_ui/test/application/services/config_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hive_ui/core/result/result.dart' as _i2;
import 'package:hive_ui/data/datasources/remote_config_source.dart' as _i3;
import 'package:hive_ui/domain/failures/auth_failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<S, F> extends _i1.SmartFake implements _i2.Result<S, F> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigDataSource extends _i1.Mock implements _i3.ConfigDataSource {
  MockConfigDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<String>, _i5.Failure>> getInterestsList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getInterestsList,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>, _i5.Failure>>.value(
            _FakeResult_0<List<String>, _i5.Failure>(
          this,
          Invocation.method(
            #getInterestsList,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>, _i5.Failure>>);

  @override
  _i4.Future<_i2.Result<List<String>, _i5.Failure>> getAllowedDomains() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllowedDomains,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<String>, _i5.Failure>>.value(
            _FakeResult_0<List<String>, _i5.Failure>(
          this,
          Invocation.method(
            #getAllowedDomains,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<String>, _i5.Failure>>);

  @override
  _i4.Future<_i2.Result<bool, _i5.Failure>> isFeatureEnabled(
          String? featureKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFeatureEnabled,
          [featureKey],
        ),
        returnValue: _i4.Future<_i2.Result<bool, _i5.Failure>>.value(
            _FakeResult_0<bool, _i5.Failure>(
          this,
          Invocation.method(
            #isFeatureEnabled,
            [featureKey],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool, _i5.Failure>>);
}
