// Mocks generated by Mockito 5.4.6 from annotations
// in hive_ui/test/application/services/verification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hive_ui/core/result/result.dart' as _i2;
import 'package:hive_ui/data/datasources/firestore_user_datasource.dart' as _i3;
import 'package:hive_ui/domain/entities/user_profile.dart' as _i5;
import 'package:hive_ui/domain/failures/auth_failure.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<S, F> extends _i1.SmartFake implements _i2.Result<S, F> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataSource extends _i1.Mock implements _i3.UserDataSource {
  MockUserDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> saveUserProfile(
    _i5.UserProfile? userProfile,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [
            userProfile,
            uid,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #saveUserProfile,
            [
              userProfile,
              uid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> getUserProfile(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #getUserProfile,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> updateUserProfile(
    String? uid,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            uid,
            updates,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #updateUserProfile,
            [
              uid,
              updates,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<bool, _i6.Failure>> isUsernameTaken(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #isUsernameTaken,
          [username],
        ),
        returnValue: _i4.Future<_i2.Result<bool, _i6.Failure>>.value(
            _FakeResult_0<bool, _i6.Failure>(
          this,
          Invocation.method(
            #isUsernameTaken,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> requestVerification(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestVerification,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #requestVerification,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<List<_i5.UserProfile>, _i6.Failure>> getUsersByUsername(
          String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersByUsername,
          [username],
        ),
        returnValue:
            _i4.Future<_i2.Result<List<_i5.UserProfile>, _i6.Failure>>.value(
                _FakeResult_0<List<_i5.UserProfile>, _i6.Failure>(
          this,
          Invocation.method(
            #getUsersByUsername,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.UserProfile>, _i6.Failure>>);
}
