// University at Buffalo specific data constants
// Extracted from mobile app constants

export const UB_MAJORS = [
  // UNDERGRADUATE PROGRAMS
  'Accounting BS',
  'Aerospace Engineering BS',
  'African-American Studies BA',
  'American Studies BA',
  'Anthropology BA',
  'Architecture BS',
  'Art History BA',
  'Asian Studies BA',
  'Biochemistry BS',
  'Bioinformatics and Computational Biology BS',
  'Biological Sciences BA',
  'Biological Sciences BS',
  'Biomedical Engineering BS',
  'Biomedical Sciences BS',
  'Biotechnology BS',
  'Business Administration BS',
  'Chemical Engineering BS',
  'Chemistry BA',
  'Chemistry BS',
  'Civil Engineering BS',
  'Classics BA',
  'Cognitive Science BA',
  'Communication BA',
  'Computational Linguistics BS',
  'Computational Physics BS',
  'Computer Engineering BS',
  'Computer Science BA',
  'Computer Science BS',
  'Criminology BA',
  'Dance BA',
  'Dance BFA',
  'Economics BA',
  'Economics BS',
  'Electrical Engineering BS',
  'Engineering Physics BS',
  'Engineering Science BS',
  'English BA',
  'Environmental Design BA',
  'Environmental Engineering BS',
  'Environmental Science BS',
  'Environmental Studies BS',
  'Environmental Sustainability BA',
  'Exercise Science BS',
  'Film Studies BA',
  'Fine Arts BFA',
  'French BA',
  'Geographic Information Science BS',
  'Geography BA',
  'Geological Sciences BA',
  'Geological Sciences BS',
  'German BA',
  'Global Affairs BA',
  'Global Gender Studies BA',
  'Health and Human Services BA',
  'History BA',
  'Indigenous Studies BA',
  'Industrial Engineering BS',
  'Information Technology and Management BS',
  'International Studies BA',
  'International Trade BA',
  'Italian BA',
  'Jewish Studies BA',
  'Law BA',
  'Legal Studies BA',
  'Linguistics BA',
  'Material Science and Engineering BS',
  'Mathematical Physics BS',
  'Mathematics BA',
  'Mathematics BS',
  'Mathematics-Economics BA',
  'Mechanical Engineering BS',
  'Media Study BA',
  'Medical Laboratory Science BS',
  'Medicinal Chemistry BS',
  'Music BA',
  'Music Performance BMus',
  'Music Theatre BFA',
  'Neuroscience BS',
  'Nuclear Medicine Technology BS',
  'Nursing BS',
  'Nutrition Science BS',
  'Occupational Therapy BS',
  'Pharmaceutical Sciences BS',
  'Pharmacology and Toxicology BS',
  'Pharmacy PharmD',
  'Philosophy BA',
  'Philosophy, Politics and Economics BA',
  'Physics BA',
  'Physics BS',
  'Political Science BA',
  'Psychology BA',
  'Psychology BS',
  'Public Health BS',
  'Sociology BA',
  'Spanish BA',
  'Special Studies BA',
  'Special Studies BS',
  'Speech and Hearing Science BA',
  'Statistics BA',
  'Studio Art BA',
  'Theatre BA',
  'Theatre BFA',
  'Urban and Public Policy Studies BA',

  // MASTERS PROGRAMS
  'Accounting MS',
  'Adult/Gerontology Nurse Practitioner DNP',
  'Advanced Education in General Dentistry Advanced Certificate',
  'Advanced Manufacturing Advanced Certificate',
  'Aerospace Engineering MS',
  'American Studies MA',
  'Anthropology and Law MA',
  'Anthropology MA',
  'Applied Biostatistics Advanced Certificate',
  'Applied Statistical Analysis Advanced Certificate',
  'Architecture MArch',
  'Arts Management MA',
  'Athletic Training MS',
  'Bilingual Education Advanced Certificate',
  'Biochemistry MA',
  'Bioinformatics and Biostatistics MS',
  'Biological Sciences MA',
  'Biological Sciences MS',
  'Biology Education: Adolescence EdM',
  'Biomaterials MS',
  'Biomedical Engineering MS',
  'Biomedical Informatics MS',
  'Biophysics MS',
  'Biostatistics MA',
  'Biotechnology MS',
  'Bridge Engineering Advanced Certificate',
  'Business Administration MBA',
  'Business Analytics MS',
  'Cancer Sciences MS',
  'Chemical Engineering ME',
  'Chemical Engineering MS',
  'Chemistry Education: Adolescence EdM',
  'Chemistry MS',
  'Childhood Education EdM',
  'Civil Engineering MS',
  'Classics MA',
  'Clinical and Translational Therapeutics MS',
  'Clinical Nutrition MS',
  'Communication MA',
  'Communicative Disorders and Sciences MA',
  'Community Health and Health Behavior MS',
  'Comparative Literature MA',
  'Computational and Applied Mathematics MS',
  'Computational Cell Biology, Anatomy and Pathology MS',
  'Computational Earth Science MS',
  'Computational Linguistics MS',
  'Computer Science and Engineering MS',
  'Computer Science Education EdM',
  'Cybersecurity Advanced Certificate',
  'Dance MFA',
  'Data Analytics in the Social Sciences MS',
  'Data Sciences and Applications MPS',
  'Econometrics and Quantitative Economics MS',
  'Economics MA',
  'Education Studies EdM',
  'Educational Culture, Policy and Society EdM',
  'Educational Data Science MS',
  'Electrical Engineering ME',
  'Electrical Engineering MS',
  'Endodontics Advanced Certificate',
  'Engineering Management ME',
  'Engineering Science MS',
  'English MA',
  'English Education Studies EdM',
  'English Education: Adolescence EdM',
  'Environmental and Water Resources Engineering MS',
  'Environmental Health Sciences MS',
  'Epidemiology MS',
  'Evolution, Ecology and Behavior MS',
  'Exercise Science MS',
  'Family Nurse Practitioner DNP',
  'Finance MS',
  'Fine Arts MFA',
  'French Language and Literature MA',
  'Genetics, Genomics and Bioinformatics MS',
  'Geographic Information Science MS',
  'Geography MA',
  'Geography MS',
  'Geological Sciences MS',
  'Global Affairs MA',
  'Global Gender Studies MA',
  'Higher Education and Student Affairs EdM',
  'Historic Preservation Advanced Certificate',
  'History MA',
  'Humanities Interdisciplinary MA',
  'Industrial Engineering MS',
  'Information and Library Science MS',
  'International Development and Global Health MS',
  'International Trade MA',
  'Jewish Thought MA',
  'Law LLM',
  'Linguistics MA',
  'Literacy Education Studies EdM',
  'Management Information Systems MS',
  'Management MS',
  'Materials Design and Innovation MS',
  'Mathematics MA',
  'Mathematics Education: Adolescence EdM',
  'Mechanical Engineering MS',
  'Media Arts and Sciences MS',
  'Media Arts Production MFA',
  'Medical Anatomy and Experimental Pathology MS',
  'Medical Physics MS',
  'Medicinal Chemistry MS',
  'Mental Health Counseling MS',
  'Microbiology and Immunology MS',
  'Music Composition MA',
  'Music Education EdM',
  'Music History MA',
  'Music Performance MM',
  'Music Theory MA',
  'Natural Science Interdisciplinary MS',
  'Neuroscience MS',
  'Nurse Anesthesia DNP',
  'Nutrition MS',
  'Occupational Therapy MS',
  'Oral Sciences MS',
  'Orthodontics MS',
  'Pharmacometrics and Personalized Pharmacotherapy MS',
  'Pharmaceutical Sciences MS',
  'Pharmacology MS',
  'Philosophy MA',
  'Physics Education: Adolescence EdM',
  'Physics MS',
  'Physiology MS',
  'Political Science MA',
  'Psychiatric/Mental Health Nurse Practitioner DNP',
  'Psychology MA',
  'Public Health MPH',
  'Real Estate Development MS',
  'Rehabilitation Counseling MS',
  'Rehabilitation Science MS',
  'School Counseling EdM',
  'School Librarianship MS',
  'School Psychology MA',
  'Social Science Interdisciplinary MS',
  'Social Studies Education: Adolescence EdM',
  'Social Work MSW',
  'Spanish Education: Adolescence EdM',
  'Spanish Language and Literature MA',
  'Structural Biology MS',
  'Supply Chain Management MS',
  'Sustainability Leadership MS',
  'Sustainable Transportation and Logistics MS',
  'Teaching English to Speakers of Other Languages EdM',
  'Theatre and Performance MA',
  'Urban Planning MUP',

  // PHD PROGRAMS
  'American Studies PhD',
  'Anthropology PhD',
  'Biological Sciences PhD',
  'Biophysics PhD',
  'Biostatistics PhD',
  'Chemistry PhD',
  'Classics PhD',
  'Comparative Literature PhD',
  'Computational and Applied Mathematics PhD',
  'English PhD',
  'Geography PhD',
  'Geological Sciences PhD',
  'Global Gender Studies PhD',
  'History PhD',
  'Linguistics PhD',
  'Mathematics PhD',
  'Philosophy PhD',
  'Physics PhD',
  'Political Science PhD',
  'Psychology PhD',
  'Sociology PhD',
  'Spanish Language and Literature PhD',
  'Urban and Regional Planning PhD',
  'Oral Biology PhD',
  'Counseling Psychology PhD',
  'Curriculum, Instruction and the Science of Learning PhD',
  'Educational Administration PhD',
  'Educational Culture, Policy and Society PhD',
  'Educational Data Science PhD',
  'Aerospace Engineering PhD',
  'Biomedical Engineering PhD',
  'Chemical Engineering PhD',
  'Civil Engineering PhD',
  'Electrical Engineering PhD',
  'Industrial Engineering PhD',
  'Mechanical Engineering PhD',
  'Engineering Science PhD',
  'Computational and Data Enabled Sciences PhD',
  'Business Administration PhD',
  'Biomedical Sciences PhD',
  'Biomedical Informatics PhD',
  'Nursing PhD',
  'Pharmaceutical Sciences PhD',
  'Pharmacology PhD',
  'Epidemiology PhD',
  'Exercise and Nutrition Sciences PhD',
  'Nutrition Science PhD',
  'Rehabilitation Science PhD',
  'Social Welfare PhD',
  'Cancer Sciences PhD',
] as const;

export const ACADEMIC_YEARS = [
  'Freshman',
  'Sophomore', 
  'Junior',
  'Senior',
  'Masters',
  'PhD',
  'Non-Degree Seeking',
] as const;

export const RESIDENCE_OPTIONS = [
  'Ellicott',
  'Governors', 
  'Greiner',
  'On Campus Apartments',
  'Commuter',
] as const;

export const SPACE_TYPES = [
  'Student Organization',
  'University Organization', 
  'Campus Living',
  'Fraternity & Sorority',
  'HIVE Exclusive',
  'Other',
] as const;

// Type definitions
export type UBMajor = typeof UB_MAJORS[number];
export type AcademicYear = typeof ACADEMIC_YEARS[number];
export type ResidenceOption = typeof RESIDENCE_OPTIONS[number];
export type SpaceType = typeof SPACE_TYPES[number]; 