// Mocks generated by Mockito 5.4.6 from annotations
// in hive_ui/test/domain/usecases/complete_onboarding_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hive_ui/core/result/result.dart' as _i2;
import 'package:hive_ui/domain/analytics/analytics_event.dart' as _i9;
import 'package:hive_ui/domain/entities/user_profile.dart' as _i5;
import 'package:hive_ui/domain/failures/auth_failure.dart' as _i6;
import 'package:hive_ui/domain/repositories/user_repository.dart' as _i3;
import 'package:hive_ui/domain/usecases/generate_username_usecase.dart' as _i7;
import 'package:hive_ui/domain/usecases/track_analytics_event_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<S, F> extends _i1.SmartFake implements _i2.Result<S, F> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> getUserProfile(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #getUserProfile,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> createUserProfile(
    _i5.UserProfile? profile,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [
            profile,
            uid,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #createUserProfile,
            [
              profile,
              uid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> updateUserProfile(
    String? uid,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            uid,
            updates,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #updateUserProfile,
            [
              uid,
              updates,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<bool, _i6.Failure>> isUsernameTaken(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #isUsernameTaken,
          [username],
        ),
        returnValue: _i4.Future<_i2.Result<bool, _i6.Failure>>.value(
            _FakeResult_0<bool, _i6.Failure>(
          this,
          Invocation.method(
            #isUsernameTaken,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>> getUserProfileByUsername(
          String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfileByUsername,
          [username],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserProfile, _i6.Failure>(
          this,
          Invocation.method(
            #getUserProfileByUsername,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserProfile, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> requestVerification(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestVerification,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #requestVerification,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> cancelVerificationRequest(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelVerificationRequest,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #cancelVerificationRequest,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<_i5.UserTier, _i6.Failure>> getVerificationStatus(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerificationStatus,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.UserTier, _i6.Failure>>.value(
            _FakeResult_0<_i5.UserTier, _i6.Failure>(
          this,
          Invocation.method(
            #getVerificationStatus,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.UserTier, _i6.Failure>>);
}

/// A class which mocks [GenerateUsernameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateUsernameUseCase extends _i1.Mock
    implements _i7.GenerateUsernameUseCase {
  MockGenerateUsernameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<String, _i6.Failure>> execute(
    String? firstName,
    String? lastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            firstName,
            lastName,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<String, _i6.Failure>>.value(
            _FakeResult_0<String, _i6.Failure>(
          this,
          Invocation.method(
            #execute,
            [
              firstName,
              lastName,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<String, _i6.Failure>>);
}

/// A class which mocks [TrackAnalyticsEventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackAnalyticsEventUseCase extends _i1.Mock
    implements _i8.TrackAnalyticsEventUseCase {
  MockTrackAnalyticsEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> execute(
          _i9.AnalyticsEvent? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [event],
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #execute,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> trackOnboardingStarted(
          {String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackOnboardingStarted,
          [],
          {#userId: userId},
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #trackOnboardingStarted,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> trackOnboardingStepCompleted({
    required String? stepName,
    required int? stepNumber,
    required int? totalSteps,
    required Duration? timeSpent,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackOnboardingStepCompleted,
          [],
          {
            #stepName: stepName,
            #stepNumber: stepNumber,
            #totalSteps: totalSteps,
            #timeSpent: timeSpent,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #trackOnboardingStepCompleted,
            [],
            {
              #stepName: stepName,
              #stepNumber: stepNumber,
              #totalSteps: totalSteps,
              #timeSpent: timeSpent,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> trackOnboardingCompleted({
    required Duration? totalTime,
    required bool? requestedVerification,
    required String? userId,
    int? interestsCount = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackOnboardingCompleted,
          [],
          {
            #totalTime: totalTime,
            #requestedVerification: requestedVerification,
            #userId: userId,
            #interestsCount: interestsCount,
          },
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #trackOnboardingCompleted,
            [],
            {
              #totalTime: totalTime,
              #requestedVerification: requestedVerification,
              #userId: userId,
              #interestsCount: interestsCount,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);

  @override
  _i4.Future<_i2.Result<void, _i6.Failure>> trackOnboardingAbandoned({
    required String? lastCompletedStep,
    required int? lastStepNumber,
    required Duration? timeSpent,
    String? userId,
    String? abandonReason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackOnboardingAbandoned,
          [],
          {
            #lastCompletedStep: lastCompletedStep,
            #lastStepNumber: lastStepNumber,
            #timeSpent: timeSpent,
            #userId: userId,
            #abandonReason: abandonReason,
          },
        ),
        returnValue: _i4.Future<_i2.Result<void, _i6.Failure>>.value(
            _FakeResult_0<void, _i6.Failure>(
          this,
          Invocation.method(
            #trackOnboardingAbandoned,
            [],
            {
              #lastCompletedStep: lastCompletedStep,
              #lastStepNumber: lastStepNumber,
              #timeSpent: timeSpent,
              #userId: userId,
              #abandonReason: abandonReason,
            },
          ),
        )),
      ) as _i4.Future<_i2.Result<void, _i6.Failure>>);
}
