# This file is generated by Flutter.
# Do not edit by hand, it has been overridden to disable plugin loading.

# Platform-specific plugin dependencies
set(FLUTTER_PLUGIN_LIST)
set(FLUTTER_FFI_PLUGIN_LIST)

# No plugins are registered for this platform
set(PLUGIN_BUNDLED_LIBRARIES)