name: hive_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^14.8.1
  flutter_slidable: ^4.0.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  http: ^1.3.0
  xml: ^6.5.0
  url_launcher: ^6.3.1
  dart_rss: ^3.0.3
  shared_preferences: ^2.5.3
  hugeicons: ^0.0.7
  flutter_staggered_animations: ^1.1.1
  auto_route: ^10.0.0
  flutter_svg: ^2.0.8
  image_picker: ^1.1.2
  glassmorphism: ^3.0.0
  timezone: ^0.10.0
  lottie: ^3.3.1
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^4.3.0
  flutter_animated_progress_bar: ^1.0.5
  add_2_calendar: ^3.0.1
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.7
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  uuid: ^4.5.1
  flutter_native_splash: ^2.3.10
  video_player: ^2.8.3
  chewie: ^1.7.1
  fl_chart: ^0.70.2
  # Image processing packages
  path: ^1.8.3
  image: ^4.1.7
  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  firebase_performance: ^0.10.1+5
  google_sign_in: ^6.1.4
  # Social authentication packages
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^6.0.4
  crypto: ^3.0.3
  # Security and encryption
  encrypt: ^5.0.3
  flutter_secure_storage: ^10.0.0-beta.4
  # Temporarily removing workmanager due to compatibility issues
  # workmanager: ^0.5.2
  connectivity_plus: ^6.1.3
  firebase_crashlytics: ^4.3.5
  mime: ^2.0.0
  get_it: ^8.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  visibility_detector: ^0.4.0+2
  flutter_blurhash: ^0.8.0
  firebase_remote_config: ^5.4.3
  package_info_plus: ^8.3.0
  palette_generator: ^0.3.3+2
  firebase_database: ^11.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  confetti: ^0.8.0
  flutter_phoenix: ^1.1.1
  photo_view: ^0.15.0
  path_provider: ^2.1.1
  timeago: ^3.7.0
  # Media handling
  file_picker: ^10.0.0
  permission_handler: ^11.4.0
  # Local notifications
  flutter_local_notifications: ^19.0.0
  web_socket_channel: ^3.0.2
  # Device info package
  device_info_plus: ^9.1.2
  lucide_icons: 0.257.0

  logging: any
  uni_links: ^0.5.1
  dartz: ^0.10.1
  phosphor_flutter: ^2.1.0
  cloud_functions: ^5.4.0
  flutter_animate: ^4.5.2
  flutter_spinkit: ^5.2.1

  # HIVE Shared Packages
  # hive_tokens: (removed - Node.js package, not Flutter)

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  mockito: ^5.4.5
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  network_image_mock: ^2.1.1
  test: ^1.24.9
  bloc_test: ^10.0.0
  path_provider: ^2.0.11
  image: ^4.1.7
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/component-6.png
    - assets/images/google.png
    - assets/images/hivelogo.png
    - assets/images/whereyoulive.png
    - assets/images/realbooks.png
    - assets/images/house.png
    - assets/images/megaphone.png
    - assets/images/hivebeaker.png
    - assets/images/circles.png
    - assets/images/year.png
    - assets/animations/