# This file is generated by Flutter.
# Do not edit by hand, it has been overridden to disable Windows plugin loading.

# Platform-specific plugin dependencies for Windows
set(FLUTTER_PLUGIN_LIST)
set(FLUTTER_FFI_PLUGIN_LIST)

# No plugins are registered for Windows platform
set(PLUGIN_BUNDLED_LIBRARIES)